networks:
  oullin_net:
    name: oullin_net
    driver: bridge

services:
    deployment:
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            args:
                - BINARY_NAME=${DOCKER_BINARY_NAME}
                - INFRA_USER=${DOCKER_INFRA_USER}
                - INFRA_GROUP=${DOCKER_INFRA_GROUP}
                - INFRA_HOST_PORT=${DOCKER_INFRA_HOST_PORT}
        container_name: oullin_infra
        restart: always
        networks:
            - oullin_net
