networks:
  oullin_net:
    name: oullin_net
    driver: bridge

services:
    deployment:
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            args:
                - APP_VERSION=v1.0.0-release
                - APP_HOST_PORT=${ENV_HTTP_PORT}
                - APP_USER=${ENV_DOCKER_USER}
                - APP_GROUP=${ENV_DOCKER_USER_GROUP}
        container_name: oullin_infra
        restart: always
        networks:
            - oullin_net
